[package]
name = "toolbelt_a"
version = "0.1.0"
authors = ["arthurDiff <arthur.lee945@gmail.com>"]
description = "Random tools for use"

[lib]

[dependencies]
proc_macro = { path = "./proc_macro", optional = true }
worker = { path = "./worker", optional = true }

[package.metadata.docs.rs]
rustdoc-args = ["--generate-link-to-definition"]

### FEATURES #################################################################

[features]
default = []
prc_mcr = ["proc_macro"]
wrk = ["worker"]
